apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooprest
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfooprest/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfooprest/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /syfooprest/internal/prometheus
  ingresses:
    - "https://syfooprest.nais.oera-q.local"
    - "https://syfooprest-q.nav.no"
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/dev/srvsyfooprest"
        mountPath: "/serviceuser/srvsyfooprest"
      - kvPath: "serviceuser/data/dev/srvsyfooprest-sbs"
        mountPath: "/serviceuser/srvsyfooprest-sbs"
      - kvPath: "/apikey/apigw/dev/security-token-service-token/syfooprest_q1"
        mountPath: "/apigw/securitytokenservicetoken"
      - kvPath: "/apikey/apigw/dev/pdl-api/syfooprest_q1"
        mountPath: "/apigw/pdlapi"
      - kvPath: "/kv/preprod/sbs/syfooprest/default"
        mountPath: "/var/run/secrets/nais.io/vault"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: APP_NAME
      value: "syfooprest"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: NON-PROD
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.oera-q.local/SecurityTokenServiceProvider/
    - name: SERVICEGATEWAY_URL
      value: https://service-gw-q1.oera-q.local/
    - name: TJENESTER_URL
      value: https://tjenester-q1.nav.no
    - name: PDL_URL
      value: https://api-gw-q1.oera.no/pdl-api/graphql
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw-q1.oera.no/security-token-service
    - name: SYFOAPI_URL
      value: https://syfoapi-q.nav.no
    - name: AKTOER_V2_ENDPOINTURL
      value: https://app-q1.adeo.no/aktoerregister/ws/Aktoer/v2
    - name: VIRKSOMHET_ARBEIDSFORHOLD_V3_ENDPOINTURL
      value: https://modapp-q1.adeo.no/aareg-services/ArbeidsforholdService/v3
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_ENDPOINTURL
      value: https://dkif.nais.preprod.local/ws/DigitalKontaktinformasjon/v1
    - name: VIRKSOMHET_ORGANISASJON_V4_ENDPOINTURL
      value: https://modapp-q1.adeo.no/ereg/ws/OrganisasjonService/v4
