apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooprest
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfooprest/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfooprest/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /syfooprest/internal/prometheus
  ingresses:
    - "https://syfooprest.nais.oera.no"
    - "https://syfooprest.nav.no"
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/prod/srvsyfooprest"
        mountPath: "/serviceuser/srvsyfooprest"
      - kvPath: "serviceuser/data/prod/srvsyfooprest-sbs"
        mountPath: "/serviceuser/srvsyfooprest-sbs"
      - kvPath: "serviceuser/data/prod/srvrestoppfoelgingsdialog-sbs"
        mountPath: "/serviceuser/srvrestoppfoelgingsdialog-sbs"
      - kvPath: "/apikey/apigw/prod/security-token-service-token/syfooprest"
        mountPath: "/apigw/securitytokenservicetoken"
      - kvPath: "/apikey/apigw/prod/pdl-api/syfooprest"
        mountPath: "/apigw/pdlapi"
      - kvPath: "/kv/prod/sbs/syfooprest/default"
        mountPath: "/var/run/secrets/nais.io/vault"
  env:
    - name: APP_NAME
      value: "syfooprest"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: PROD
    - name: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_ACCEPTEDAUDIENCE
      value: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25
    - name: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_DISCOVERYURL
      value: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.oera.no/SecurityTokenServiceProvider/
    - name: SERVICEGATEWAY_URL
      value: https://service-gw.oera.no/
    - name: TJENESTER_URL
      value: https://tjenester.nav.no
    - name: PDL_URL
      value: https://api-gw.oera.no/pdl-api/graphql
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw.oera.no/security-token-service
    - name: SYFOAPI_URL
      value: https://syfoapi.nav.no
    - name: AKTOER_V2_ENDPOINTURL
      value: https://app.adeo.no/aktoerregister/ws/Aktoer/v2
    - name: VIRKSOMHET_ARBEIDSFORHOLD_V3_ENDPOINTURL
      value: https://modapp.adeo.no/aareg-services/ArbeidsforholdService/v3
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_ENDPOINTURL
      value: https://dkif.nais.adeo.no/ws/DigitalKontaktinformasjon/v1
    - name: VIRKSOMHET_ORGANISASJON_V4_ENDPOINTURL
      value: https://modapp.adeo.no/ereg/ws/OrganisasjonService/v4
